classes:
  - name: Barbarian
    location:
      world: spawn
      x: 51.5
      y: 2.0
      z: -100.5
      yaw: -152.1
      pitch: 2.1
  - name: Archer
    location:
      world: spawn
      x: -105.5
      y: 70
      z: 82.5
      yaw: 54.0
      pitch: 0.2
  - name: Archmage
    location:
      world: spawn
      x: -135.5
      y: 19
      z: -185.5
      yaw: 156.0
      pitch: -0.3
  - name: Summoner
    location:
      world: spawn
      x: -188.5
      y: 34
      z: -28.5
      yaw: 124.0
      pitch: 0.7
  - name: Illusionist
    location:
      world: spawn
      x: 46.5
      y: -11
      z: 153.5
      yaw: -52.0
      pitch: 1.7
  - name: Bard
    location:
      world: spawn
      x: -11.5
      y: 3
      z: 45.5
      yaw: -64.0
      pitch: -4.8
  - name: Monk
    location:
      world: spawn
      x: -167.0
      y: 152
      z: -17.0
      yaw: 109.0
      pitch: 4.9

default-class: Barbarian
cooldown-ms: 1000
preview-slot: 5
preview-sound: "rpg:rpg.classsong"
target-server: "RPG"

screeneffect:
  color: BLACK
  fade-in: 10
  stay: 20
  fade-out: 10
  freeze: true

kick-delay-ticks: 120
kick-message: "Server is full!"
