name: SpectatorScrollAction
version: 1.0
main: arcane.classes.plugin.ClassSelector
api-version: 1.21
soft-depend: [ProtocolLib, MMOProfiles, MMOCore]
commands:
  classselector:
    description: Opens the class selector
  adminclass:
    description: Exit class selector mode
  runserver:
    description: Sends the player to another server
    usage: /runserver <server>